export const GET_ALL_RUBROS = "GET_ALL_RUBROS";
export const GET_SUB_FROM_RUBRO = "GET_SUB_FROM_RUBRO";
export const GET_ALL_SUB_RUBROS = "GET_ALL_SUB_RUBROS";
export const FILTER_BY_RUBRO = "FILTER_BY_RUBRO";